version: '3'

services:
  db:
    image: postgres
  app:
    build: .
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
