version: '3'

services:
  db:
    image: postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    ports:
      - "8000:8000"
    depends_on:
      - db
