# Generated by Django 2.2.7 on 2019-12-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0003_auto_20191111_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
