# Generated by Django 2.2.7 on 2019-12-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0004_transaction_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
